# Generated by Django 4.1 on 2022-09-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_categoria_productos_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='unidades',
            new_name='unidades_disponibles',
        ),
    ]
